### ISSUE TITLE
Axis labels disappear when scrolling

### ISSUE THREAD

**Issue by Qlikmeister** [ralfbecher/QlikSense_Extension_Timeline#13]
A really cool extension that's highly configurable, though we have found one issue:

If a number of records is loaded that needs a right hand scroll to navigate vertically, the axis labels disappear when scrolling between top and bottom records. Is it possible to fix/configure this?

**Comment by ralfbecher** [comment]
Yea, agree we should have a fixed size so axis labels are always visible.

However, we should probably also have vertical scroll instead of zoom in: 
http://visjs.org/examples/timeline/other/verticalScroll.html

**Comment by ralfbecher** [comment]
I've fixed this please have a try.

Will add vertical scroll as an option later. I think with this option zoom on mobile devices could be an issue..
