### ISSUE TITLE
Blank Chart After Adding Measures and Dims

### ISSUE THREAD

**Issue by Feras85** [ralfbecher/QlikSense_Extension_Timeline#14]
Hello,

First thanks for a helpful chart. Unfortunately, I was not able to use it after adding the Dims and Measures just like you mentioned, I get a blank white chart. My start and end dates have long duration (activities can start 2012 and finish in 2015).

**Comment by Feras85** [comment]
Here is a sample data that produces the same issue:


[Qlik Sense Timeline Visualization(487ea2e5-00b9-48d6-b351-f6a629fffcd9).xlsx](https://github.com/ralfbecher/QlikSense_Extension_Timeline/files/795639/Qlik.Sense.Timeline.Visualization.487ea2e5-00b9-48d6-b351-f6a629fffcd9.xlsx)

**Comment by ralfbecher** [comment]
Can you attach your app file .qvf

**Comment by Feras85** [comment]
It doesn't accept the QVF file nor does it accept the  .ZIP file.

**Comment by bobocharbo** [comment]
Hi, just as @Feras85, I can't manage to display the timeline, all I got is a blank white chart. I'm using Qlik Sense 3.2. 

I have a table named Event_Monitor, in which I can find : 

- Event Id : First Dimension
- Event Info : Second Dimension
- Event Start Date : Third Dimension
- Event End Date : Fourth Dimension

Still I didn't understand what should I put in the fith dimension. 

I also add the measures just like you mentioned, i.e : a number defining the css class. 

My first question is : Is it compatible with Qlik 3.2 ?
And of couse, does someone see something obvious I missed ?

**Comment by ralfbecher** [comment]
Yes it works with v3.2. For fith dimension you need to set Item Type (box (default), point, range, background) eg.:
='box'
