### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by Exojolt** [ralfbecher/QlikSense_Extension_Timeline#16]
Hi there! Not sure if it is an issue.. However, is it possible to get a horizontal scrollbar to scroll between the times instead of having a drag-x function?

Best regards,
Exojolt

**Comment by ralfbecher** [comment]
Hi, I think there is no scrollbar since the object size is same as extension. But using buttons could probably help: http://visjs.org/examples/timeline/interaction/navigationMenu.html

**Comment by Kara1322** [comment]
Are you able to provide direction on how you created the zoom buttons?

**Comment by ralfbecher** [comment]
Just look into the source of the link above and copy the javascript code..

**Comment by Kara1322** [comment]
Thx!  I'm actually looking for a potential solution for a vertical scroll of some sort.  Our higher level project overview contains a number of projects and it's difficult for the user to 'scroll' down thru the projects but 'pushing' down through the object.  I tried to look for potential slider or other alternate external solution for a vertical scroll, but there's nothing out there; any thoughts?  Thx again for all your help!

**Comment by oatesch** [comment]
Check out https://github.com/almende/vis/issues/273

**Comment by Exojolt** [comment]
Thank you.

**Comment by Exojolt** [comment]
This doesn't work, as described in the VIS documentation, adding

`horizontalscroll:true,`

within var options does not do a thing.

Please advise.

**Comment by ralfbecher** [comment]
You can try this (read the vis docu !!): 

horizontalScroll: true,
zoomable: false,
                        
However, there is no horizontal scroll bar released yet !!

**Comment by Exojolt** [comment]
Do you know when this will be implemented?

**Comment by ralfbecher** [comment]
Sie link above. It's implemented but not in release yet..
