### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Kara1322** [ralfbecher/QlikSense_Extension_Timeline#17]
Is there any way to correct the font size on the pop-ups?  My company recently reloaded the timeline to allow for the stacking option; however, now the font size on the popup is very large (previously it worked fine, with font size in line with the pop-up).

Also, when you utilize the grouping option, it then limits the number of items you can see within each group.  I've tried changing the 'max items to render', to no avail.  Any way to correct for this issue?

Thx!

**Comment by ralfbecher** [comment]
I do see no difference in the font size for stacked or unstacked items.

The limit of number of items is related to the hypercube page which can contain 10k data points only. With 8 columns this is 1250 rows only. A pro version will contain data paging and more features. But you can extend this yourself and load more data pages.

**Comment by Kara1322** [comment]
Sorry, should have clarified.  The font is fine on the 'main' calendar view.  It only affects the popup text - when you use the measure for the pop-up, that's where the font becomes much larger (and bolded).

**Comment by ralfbecher** [comment]
Still don't get it. Any screenshot?

**Comment by Kara1322** [comment]
Sorry, I'm unable to get a screenshot to see the 'hover'.  Maybe another clue for you is that the character return (chr(13)) is no longer working either (was working fine before)?

**Comment by ralfbecher** [comment]
Yes, now you can use <br>
