### ISSUE TITLE
Unsure how to get started - Blank Chart

### ISSUE THREAD

**Issue by danjdo** [ralfbecher/QlikSense_Extension_Timeline#19]
Hello,

I can't seem to get anything to display.

We are using Qlik Sense 3.1 SR3.
Have an inline table such as:

Unit, AC, Event, Reason, StartDateTime, EndDateTime
Plant1,0,Outage,Maintenance,07/31/2017 6:00:00 AM, 07/31/2017 8:00:00 AM
...

I tried populating the dimensions and measures and put ='box' etc. but it still won't display.
Can you give an example of what needs to go in each dimension and measure to get displayed?

**Comment by ralfbecher** [comment]
Please have a look into the Timeline.qvf sample app..
