### ISSUE TITLE
Unable to set/see connector line to the date

### ISSUE THREAD

**Issue by danjdo** [ralfbecher/QlikSense_Extension_Timeline#20]
Hello,

This visualization is fantastic. I managed to get it all working, and referred to the QVF demo file. One thing I can't get working is the line and dot that connects the box to the date legend.

**Comment by fabiolafg** [comment]
I think you're talking about the events in the demo app that have a connector and a dot at the end. Those ones appear if you have an event with only start date. (At least that's how I've done it...)
