### ISSUE TITLE
Setting range

### ISSUE THREAD

**Issue by gfmarafon** [ralfbecher/QlikSense_Extension_Timeline#22]
Hello, first of all, congratulations, this is an excellent extension.

I am trying to make a "52 week" gant-like cronogram and i need to show only the 52 weeks, i managed that in the zoom min/ zoom max specs.

The problem is: when i do that, it shows the timeline only in months, and i needed it to show by weeks, specificaly by sundays.

I looked around the .css and .js but cound't find the solution, is there anyway i can do that?

Thank you!

**Comment by ralfbecher** [comment]
I think it's the standard behavior showing less information on a bird's view level. Maybe solved when increasing object size on sheet.
