### ISSUE TITLE
Task sorting

### ISSUE THREAD

**Issue by guventum** [ralfbecher/QlikSense_Extension_Timeline#24]
Hi, 

I would like to know how I can sort the items in a group. I know how to sort the groups but I can't seem to find an option to sort the tasks/items. 

Kind regards, 

Guven Tum

**Comment by ralfbecher** [comment]
Hi Guven,
the version in Branch:dev has a sorting option (by start or id):
https://github.com/ralfbecher/QlikSense_Extension_Timeline/tree/dev
- Ralf
