### ISSUE TITLE
Additional information columns

### ISSUE THREAD

**Issue by joelbrocklehurst** [ralfbecher/QlikSense_Extension_Timeline#25]
Hi,

I am considering adding additional columns to the timeline to contain some more data. I am currently using a table next to it, but they are no aligned and it looks messy.

Is it possble to link the timeline to the table, or is it possible to add some additional information columns to the timeline?

Thing this extension is great btw

Joel

**Comment by ralfbecher** [comment]
Hi Joel,

what you would need the additional data for? It is not possible to link the extension to a table but you can add fields in the title measure..

Ralf

**Comment by joelbrocklehurst** [comment]
Hi Ralf,

Thanks for the quick reply. I have a project view, so in the column I have the project name, then the project timeline displayed. There is some additional info I would like to display, like project status, project budget etc. No more than three or four columns. 

How would I add additional measures?

Joel

**Comment by ralfbecher** [comment]
You can either put it in 2nd dimension (content) as a concatenation field1 & field2 or in the first measure (title) as MinString(field1) & MinString(field2). Just have a look into the sample app.

**Comment by joelbrocklehurst** [comment]
Hi Ralf,

Thank's for your help, it's been very useful.

I am struggling to include a certain data field in the timeline information column. I have attached an image, the table and timeline are both using the same field as a measure, yet the timeline displays zero. 

Any idea why?

Thanks,

Joel
![slippage](https://user-images.githubusercontent.com/23475131/31399850-8ffa765a-ade5-11e7-8160-e2fe62d6df73.PNG)

**Comment by ralfbecher** [comment]
Still don't get it. Do you want to show a measure in the group label? I think this will not work.

**Comment by joelbrocklehurst** [comment]
Hi Ralf. That was the plan but we have built around it.

Another requirement I have is to be able to change the colour of the dots which do not have a border. I know this is not supported in the main functionality so I have been looking in the script but can’t find where it’s declared. Would it be possible to give me a pointer?

Joel
