### ISSUE TITLE
Unable to upload the extension

### ISSUE THREAD

**Issue by RonyBeainy** [ralfbecher/QlikSense_Extension_Timeline#26]
Hi. I am failing to upload this extension to click sense. it is giving me an error. can someone help me please?

**Comment by ralfbecher** [comment]
What Sense version and what error?

**Comment by RonyBeainy** [comment]
Good morning.

We have Qlik Sense 3.2, and below is the error message

Thank you for your reply
Rony
[cid:image001.png@01D34BD6.15A1B4C0]

**Comment by RonyBeainy** [comment]
I appreciate your support since I liked a lot the extension!!

**Comment by ralfbecher** [comment]
I don't see the image here..

**Comment by RonyBeainy** [comment]
Hi Again. How can I show you the error message please?

Thank you
Rony

**Comment by ralfbecher** [comment]
Don't use email, just go the issue here: [https://github.com/ralfbecher/QlikSense_Extension_Timeline/issues/26](https://github.com/ralfbecher/QlikSense_Extension_Timeline/issues/26)
..and attache files by dragging & dropping

**Comment by RonyBeainy** [comment]
Here you go

Thank you
![captureext](https://user-images.githubusercontent.com/32974827/32213628-09327cb4-be2d-11e7-8a6e-66ede1395c3d.JPG)

**Comment by ralfbecher** [comment]
Now it's clear. You try to upload the complete repository which is wrong. Inside of the repo (this zip file) you will find the extension file for upload: bi-irregular-timeline.zip

**Comment by RonyBeainy** [comment]
I did with same error message
![capture2](https://user-images.githubusercontent.com/32974827/32219447-4b182496-be3f-11e7-8714-2a716451e5f1.JPG)

**Comment by ralfbecher** [comment]
My guess is the extension already exists. Please delete it in QMC before the upload.

**Comment by RonyBeainy** [comment]
Thank you; it worked
