### ISSUE TITLE
Extension Timline question

### ISSUE THREAD

**Issue by Haloschlumpf** [ralfbecher/QlikSense_Extension_Timeline#29]
Hello Mr. Becher,

i really like you extension and its exactly what i searched for. But no i have a problem and i hope you can explaine it to me.

the diagram shows only one dataset or line per name/id. So if there are more dates than just one it doesnt show anyting. i'd like to have the different dates per name/id stacked over each other...
or is there any option to do so?

i'm looking forward for your answer.

Thank you really much.

Best regards
Marcel

**Comment by Haloschlumpf** [comment]
for every event is only one datefield possible. it would be great if additional dates could be stacked

**Comment by ralfbecher** [comment]
The ID (1st dimension) has to be unique per item! So, a name would be not the right choice..

**Comment by Haloschlumpf** [comment]
okay. but nevertheless there can't be more than one date per ID?

**Comment by Haloschlumpf** [comment]
thank you for your quick answer :)
