### ISSUE TITLE
Re-authenticate prompt

### ISSUE THREAD

**Issue by johnsacco** [ralfbecher/QlikSense_Extension_Timeline#3]
Hi Ralph,
   Great extension! I am having an issue on Qlik Sense 3.0.1 on an environment where we are authenticating through ADFS and when I navigate to a sheet with the timeline chart my browser (chrome) prompts me to re-authenticate. Once I authenticate this does not prompt me again until my next session. I wanted you to be aware since this isn't happening with other extensions.

**Comment by ralfbecher** [comment]
Cannot recreate the issue. No idea..

**Comment by waltermo** [comment]
Hi Ralph,

Amazing extension. I've used it on a 2.2 server without any issue, then we upgraded to 3.0.2 and I have the  same Authentication windows that pops up _after the load of the extension in a sheet. Clicking cancel on the window make the window go away but I can't go live with this issue.

Any idea how to investigate this?

thanks,

W

**Comment by ralfbecher** [comment]
Still cannot re-ceate the issue. Could you do some more investigation by looking into chrome dev tools if anything strange happen in network? Also, is this occurring with Sense standard client or in a mashup? Is it perhaps related to any Chrome extension?

**Comment by waltermo** [comment]
Hi Ralf,

This is happening in Sense Standard client.

I’ll investigate with dev tools.

Thanks,

[cid:image001.jpg@01D22AD2.94006BC0]
Walter Moraine
Section Manager
Customer Success – Business System & Infrastructure
140 Kendrick Street. Needham, MA 02494
t:   +1.781.370.5449

m: +1.857.928.7526
e:  wmoraine@PTC.com<mailto:wmoraine@PTC.com>

**Comment by waltermo** [comment]
Hi,

With the dev tool I could identify that the authentication pop up is initiated by the weekend CSS files…

When I deactivated the Mark Weekend the pop up doesn’t show up.

When looking at the details in dev tools it’s like the css is not called the same way the others are before – a param seems missing… the session token maybe?
[cid:image003.png@01D22DE4.91FB61D0]

Any Idea?

Thanks,
[cid:image001.jpg@01D22DE4.91FE6F10]
Walter Moraine
Section Manager
Customer Success – Business System & Infrastructure
140 Kendrick Street. Needham, MA 02494
t:   +1.781.370.5449

m: +1.857.928.7526
e:  wmoraine@PTC.com<mailto:wmoraine@PTC.com>



From: Moraine, Walter
Sent: Thursday, October 20, 2016 1:05 PM
To: 'ralfbecher/QlikSense_Extension_Timeline' <reply@reply.github.com>; ralfbecher/QlikSense_Extension_Timeline <QlikSense_Extension_Timeline@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [ralfbecher/QlikSense_Extension_Timeline] Re-authenticate prompt (#3)

Hi Ralf,

This is happening in Sense Standard client.

I’ll investigate with dev tools.

Thanks,

[cid:image004.jpg@01D22DE2.B53F2980]
Walter Moraine
Section Manager
Customer Success – Business System & Infrastructure
140 Kendrick Street. Needham, MA 02494
t:   +1.781.370.5449

m: +1.857.928.7526
e:  wmoraine@PTC.com<mailto:wmoraine@PTC.com>

**Comment by ralfbecher** [comment]
Hi Walter,
thanks! Have to reimplement the weekend coloring.
As a workaround you could turn off "Mark Weekend".
- Ralf

**Comment by waltermo** [comment]
Yep - i'm going to use this workaround.

thanks!

**Comment by ralfbecher** [comment]
Have fixed it. Please re-test.

**Comment by waltermo** [comment]
Hi Ralf,

It works!

Great job Ralf.

[cid:image001.jpg@01D22F68.FCCEA0F0]
Walter Moraine
Section Manager
Customer Success – Business System & Infrastructure
140 Kendrick Street. Needham, MA 02494
t:   +1.781.370.5449

m: +1.857.928.7526
e:  wmoraine@PTC.com<mailto:wmoraine@PTC.com>
