### ISSUE TITLE
Javascript Error in app

### ISSUE THREAD

**Issue by brofey** [ralfbecher/QlikSense_Extension_Timeline#33]
Greetings! 
Defenetely great extension, worked perfectly, but i've got this strange error today after aploading other set of data into app.

Are there any restrictions? 

Error statement:
> require.js:1 Error: Cannot add item: item with id 1145 already exists
>     at n._addItem (/extensions/bi-irregular-timeline/scripts/vis-fix2628.min.js?1509389618675:27)
>     at n.add (/extensions/bi-irregular-timeline/scripts/vis-fix2628.min.js?1509389618675:27)
>     at new n (/extensions/bi-irregular-timeline/scripts/vis-fix2628.min.js?1509389618675:27)
>     at DefaultView.paint (/extensions/bi-irregular-timeline/bi-irregular-timeline.js?1509389618675:644)
>     at /resources/assets/client/client.js?1509389618675:1
>     at a (require.js:1)
>     at require.js:1
>     at f.$eval (require.js:1)
>     at f.$digest (require.js:1)
>     at f.$apply (require.js:1)
> (anonymous) @ require.js:1

**Comment by ralfbecher** [comment]
I think the item id is not unique here..
