### ISSUE TITLE
Group Sorting

### ISSUE THREAD

**Issue by gino2780** [ralfbecher/QlikSense_Extension_Timeline#34]
Hello,

great Extension!

But i have an issue with the "Group Sorting" function. 
1. Which dimension slot is the grouping variable when you setup the diagram initially in the edit mode?
2. I can't seem to figure out how the timeline parts can be grouped in the diagram, like in your sample pictures.

**Comment by ralfbecher** [comment]
"Group" is the third measure. So, eg. an expression like:

= MaxString(<myfield>)
