### ISSUE TITLE
Moment.lang is not a function

### ISSUE THREAD

**Issue by changeling76** [ralfbecher/QlikSense_Extension_Timeline#4]
Hi Ralph,
Great extension!We have an issue when locale is different from default and after reloading page (i.e. after navigating back to the page).

TypeError: moment.lang is not a function 
... at paint (http://localhost:4848/extensions/bi-irregular-timeline/bi-irregular-timeline.js??1466065727840:621:30)
... at Component.TimeAxis.setOptions (http://localhost:4848/extensions/bi-irregular-timeline/scripts/vis-localized.js??1466065727840:20330:18)

It ruins the chart and sets the PL locale. The only way to make it stable is to comment the locale option in paint.

**Comment by ralfbecher** [comment]
Hi,
I have seen this behavior in some situations and in some browsers but cannot reproduce. Please try to new version with the proposed fix.

**Comment by changeling76** [comment]
Nope. The same error. 
And still get the warning "Accessing Moment through the global scope is deprecated, and will be removed in an upcoming release." Browsers Chrome and Safari.

**Comment by ralfbecher** [comment]
But how to reproduce? However, this warning doesn't matter..

**Comment by ralfbecher** [comment]
Btw. have you cleared your broser cache?

**Comment by changeling76** [comment]
Yes, I cleared it. Sent you a test app by email.

**Comment by ralfbecher** [comment]
Another change to fix this. Please try again..

**Comment by changeling76** [comment]
same...

**Comment by ralfbecher** [comment]
This solved the issue with your app on my side.

**Comment by changeling76** [comment]
it's like a heisenbug. Seems to work in QS Desktop. But when accessing from Chrome - it happens after 2-5 reloads....

**Comment by ralfbecher** [comment]
Another change. Please try again.

**Comment by changeling76** [comment]
same.. :(

**Comment by ralfbecher** [comment]
Now this should(!) it be.

**Comment by changeling76** [comment]
yesss! it works 👍 Thanks!
