### ISSUE TITLE
Qlik Sense Beginner - I don't know how to parameter the extension

### ISSUE THREAD

**Issue by raymar13** [ralfbecher/QlikSense_Extension_Timeline#7]
Hello,

I am a new Qlik Sense user and beginning in BI, and I am very satisfied that an extension like this one exists, adding a key fonctionnalty to Qlik Sense.

But I am sorry since there is no tutorial, i don't know why it works when I am using previsionnal project dates, but it doesn't when i use effective/Real projet dates.

I also don't know how to add several events, like in your Gif, one as range, another as point Since there are only 5 dimensions, so i can only set 1 event.

Thank you again for your application and, I hope, for your help.

**Comment by ralfbecher** [comment]
Please use provided sample application to see how to use extension with data and take care of feeding proper data to the hypercube. I don't know what do you mean by adding events. The Gifs just showing standard mouse events.

**Comment by raymar13** [comment]
Since I am using Qlik Sense Enterprise, i can't open a Qvf file.

**Comment by ralfbecher** [comment]
You need to import it via QMC. Ask you admin..

**Comment by raymar13** [comment]
okay, thank you for your incredibly fast answer and your useful application.

**Comment by ralfbecher** [comment]
You can also download Qlik Sense Desktop for free to use locally.
