### ISSUE TITLE
only 3 group is showing

### ISSUE THREAD

**Issue by bravicha** [ralfbecher/QlikSense_Extension_Timeline#8]
Hi,

the extension is showing only 3 groups. need to show all groups by default.

thanks.

**Comment by ralfbecher** [comment]
There is no limitiation of showing groups. This is probably related to the data.

**Comment by bravicha** [comment]
[codeWork1.xlsx](https://github.com/ralfbecher/QlikSense_Extension_Timeline/files/719244/codeWork1.xlsx)
[bi-irregular-timeline.zip](https://github.com/ralfbecher/QlikSense_Extension_Timeline/files/719245/bi-irregular-timeline.zip)

[TimelineEdited.zip](https://github.com/ralfbecher/QlikSense_Extension_Timeline/files/719246/TimelineEdited.zip)


Hi I have attached the App and data. Please help. in other bar chart it is coming without issues

**Comment by ralfbecher** [comment]
The extension is limited to process 10k data points. In this case it's 1250 rows by max. 8 fields. To see more groups you need to reduce (select) your data, eg. by date.
