### ISSUE TITLE
Extension doesn't work with mashup

### ISSUE THREAD

**Issue by paulcalvet** [ralfbecher/QlikSense_Extension_Timeline#9]
Hi Ralf,

It seems that your (great) extensions doesn't work embeded on mahsup.
Do you have the same problem ?
Is it normal ?

Thanks

Paul

**Comment by ralfbecher** [comment]
Hi Paul,
this is a module loading issue with moment.js. Have no idea how to solve.
- Ralf

**Comment by ralfbecher** [comment]
Got help from https://github.com/mindspank who provided a fix for vis.js, see issue
https://github.com/almende/vis/issues/2628

**Comment by paulcalvet** [comment]
Thank you Ralf !
That's work now.
Paul
